services:
  backend:
    build: ./backend
    container_name: daisy-backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: daisy-frontend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
  image: nginx:latest
  container_name: daisy-nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/ssl/sonchasapps.crt:/etc/ssl/sonchasapps.crt:ro
    - /etc/ssl/sonchasapps.key:/etc/ssl/sonchasapps.key:ro
  depends_on:
    - backend
    - frontend
  restart: unless-stopped
